osx_image: xcode11
language: swift
script:
    - xcodebuild clean test -workspace UberCarAnimation.xcworkspace -scheme UberCarAnimation -destination 'platform=iOS Simulator,OS=12.0,name=iPhone 7'  CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet