osx_image: xcode11
language: swift
script:
    - xcodebuild clean test -workspace UberCarAnimation.xcworkspace -scheme UberCarAnimation -destination 'platform=iOS Simulator,OS=10.1,name=iPad Pro (9.7-inch)'  CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet