osx_image: xcode11
language: swift
script:
    - xcodebuild clean test -workspace UberCarAnimation.xcworkspace -scheme UberCarAnimation -destination "platform=iOS Simulator,name=iPhone 7,OS=12.0" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet